config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    member do
      get 'add_category/:category_id', :action => 'add_category', as: :add_category
      get 'remove_category/:category_id', :action => 'remove_category', as: :remove_category
    end
  end
  resources :partners
  resources :customers

  scope "(:locale)", locale: /pt-BR|en|es/ do
    resources :general_contacts, only: [:create], :path => "contato"
    root to: 'pages#home'
  end
  devise_for :users

  get 'webhooks/social_links', to: 'webhooks#social_links'
  get 'webhooks/indexes', to: 'webhooks#indexes'
  get 'webhooks/projects', to: 'webhooks#projects'

  match '*path', via: :get, to: redirect('/')
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string
#  type        :string
#  image       :string
#  summary     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  thumb_image :string
#  sort_order  :integer
#  slug        :string
#

class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  attr_accessor :selected_categories

  has_many :project_owners, dependent: :destroy
  has_many :owners, through: :project_owners, foreign_key: "project_id", class_name: "Person"

  has_many :project_categories, dependent: :destroy
  has_many :categories, through: :project_categories

  mount_uploader :image, StandardImageUploader
  mount_uploader :thumb_image, StandardImageUploader

  validates_presence_of :name, :thumb_image, :image, :sort_order

  after_save :check_category_ids

  translates :summary

  def selected_categories
    @selected_categories || []
  end

  def has_category(category)
    categories.find_by(id: category.id).present?
  end

  protected
    def check_category_ids
      if selected_categories && ! selected_categories.empty?
        selected_categories.each do |category_id|
          self.project_categories.find_or_create_by(category_id: category_id)
        end
      end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html, :json
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_project, only: [:show, :edit, :update, :destroy, :add_category, :remove_category]

  # POST /projects
  def show
    respond_to do |format|
      format.html { redirect_to root_path(anchor: @project.slug) }
      format.json { respond_with(@project) }
    end
  end

  # POST /projects/1/add_category?category_id=1
  def add_category
    @project_category = ProjectCategory.find_or_create_by(project: @project, category_id: params[:category_id])

    respond_to do |format|
      format.html { redirect_to root_path(anchor: @project.slug) }
      format.json { respond_with(@project_category) }
    end
  end

  # POST /projects/1/remove_category?category_id=1
  def remove_category
    @project_category = ProjectCategory.find_by(project: @project, category_id: params[:category_id])
    @project_category.destroy if @project_category

    respond_to do |format|
      format.html { redirect_to root_path(anchor: @project.slug) }
      format.json { respond_with(@project) }
    end
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      respond_to do |format|
        format.html { redirect_to root_path(anchor: @project.slug) }
        format.json { respond_with(@project) }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      respond_with @project
    else
      respond_to do |format|
        format.html { redirect_to root_path(anchor: @project.slug) }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  def destroy
    if @project.destroy
      head :no_content
    else
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name, :type, :image, :image_cache, :thumb_image, :thumb_image_cache, :summary, :sort_order, selected_categories: [])
    end
end

app/views/projects/_form.html.slim
= simple_form_for(project) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    / = f.input :type
    = f.input :image
    = f.input :selected_categories, as: :check_boxes, collection: @categories, multiple: true
    = f.input :summary, as: :text
    = f.input :thumb_image
    = f.input :sort_order

  .form-actions
    = f.button :submit

app/views/projects/_list.html.slim
section#portfolio
  .spin-loading
    img src="#{image_path('loading.gif')}" alt="Loading..."
  .sub-menu
    .sub-menu-links
      a.open-related-portfolio href="#related-portfolio"
        img src="#{image_path('icon-portfolio-related.png')}" title="#{@global_page.get_value('global.header.related_portfolio', 'Projetos Similares').value}"
      a.close-portfolio href="" title="#{t('global.close')}"
        img src="#{image_path('icon-close-menu.png')}" alt="#{t('global.close')}"
  .content
    nav
      ul.projects
        - @projects.each do |project|
          li.project.project-thumb class="#{@can_edit ? 'admin' : ''}"
            a.open-project.item-container href="##{project.slug}" style="background-image:url(#{project.thumb_image})"
              .info
                .name
                  strong = project.name
                span.producer 
                  | by&nbsp;
                  span.nucleo nucleo
              img src="#{project.thumb_image}"
        - if @can_edit
          li.new
            a.open-new-project href="#new-project" Novo Projeto

    - if @can_edit
      #new-project
        = render partial: 'projects/form', locals: { project: @new_project }

    - if @projects.length > 0
      .project-container
        .list-container
          .project-list
            .project-slick
              - @projects.each do |project|
                .project-item id="#{project.slug}" class="#{@can_edit ? 'admin' : ''}"
                  .info
                    .name
                      strong.name-value = string_editor(project, :name)
                    span.producer 
                      | by&nbsp;
                      span.nucleo nucleo
                    .summary.summary-value
                       = text_editor(project, :summary)
                  .categories
                    ul
                      - if @can_edit
                        - @categories.each do |category|
                          - has_category = project.has_category(category)
                          - title = has_category ? "Remover #{category.name}" : "Adicionar #{category.name}"
                          - toggle_url = has_category ? remove_category_project_path(id: project.id, category_id: category.id) : add_category_project_path(id: project.id, category_id: category.id)
                          li.editable class="#{category.icon_klass} #{has_category ? 'active' : 'disabled'}"
                            a href="#{toggle_url}" title="#{title}"
                              span = category.name
                              svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44.08 44.08"
                                | <defs><style>.cls-1{fill:#022a3a;}</style></defs><title>#{category.name}</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><rect class="cls-1" x="20.28" width="3.53" height="3.53"/><rect class="cls-1" x="14.1" width="3.53" height="3.53"/><rect class="cls-1" x="26.45" width="3.53" height="3.53"/><rect class="cls-1" x="40.55" y="26.43" width="3.53" height="3.53"/><path class="cls-1" d="M39.67,0H32.62V3.53h7.05a.89.89,0,0,1,.88.88v7h3.53v-7A4.42,4.42,0,0,0,39.67,0Z"/><rect class="cls-1" x="40.55" y="14.09" width="3.53" height="3.53"/><rect class="cls-1" x="14.1" y="40.55" width="3.53" height="3.53"/><rect class="cls-1" x="40.55" y="20.26" width="3.53" height="3.53"/><rect class="cls-1" y="26.43" width="3.53" height="3.53"/><path class="cls-1" d="M3.53,39.67V32.6H0v7.07a4.42,4.42,0,0,0,4.41,4.41h7.05V40.55H4.41A.89.89,0,0,1,3.53,39.67Z"/><rect class="cls-1" y="14.09" width="3.53" height="3.53"/><rect class="cls-1" x="20.28" y="40.55" width="3.53" height="3.53"/><path class="cls-1" d="M40.55,39.67a.89.89,0,0,1-.88.88H32.62v3.53h7.05a4.42,4.42,0,0,0,4.41-4.41V32.6H40.55Z"/><rect class="cls-1" x="26.45" y="40.55" width="3.53" height="3.53"/><path class="cls-1" d="M3.53,4.41a.89.89,0,0,1,.88-.88h7.05V0H4.41A4.42,4.42,0,0,0,0,4.41v7H3.53Z"/><rect class="cls-1" y="20.26" width="3.53" height="3.53"/></g></g>
                      - else 
                        - project.categories.each do |category|
                          li.active class="#{category.icon_klass}"
                            span = category.name
                            svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44.08 44.08"
                              | <defs><style>.cls-1{fill:#022a3a;}</style></defs><title>#{category.name}</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><rect class="cls-1" x="20.28" width="3.53" height="3.53"/><rect class="cls-1" x="14.1" width="3.53" height="3.53"/><rect class="cls-1" x="26.45" width="3.53" height="3.53"/><rect class="cls-1" x="40.55" y="26.43" width="3.53" height="3.53"/><path class="cls-1" d="M39.67,0H32.62V3.53h7.05a.89.89,0,0,1,.88.88v7h3.53v-7A4.42,4.42,0,0,0,39.67,0Z"/><rect class="cls-1" x="40.55" y="14.09" width="3.53" height="3.53"/><rect class="cls-1" x="14.1" y="40.55" width="3.53" height="3.53"/><rect class="cls-1" x="40.55" y="20.26" width="3.53" height="3.53"/><rect class="cls-1" y="26.43" width="3.53" height="3.53"/><path class="cls-1" d="M3.53,39.67V32.6H0v7.07a4.42,4.42,0,0,0,4.41,4.41h7.05V40.55H4.41A.89.89,0,0,1,3.53,39.67Z"/><rect class="cls-1" y="14.09" width="3.53" height="3.53"/><rect class="cls-1" x="20.28" y="40.55" width="3.53" height="3.53"/><path class="cls-1" d="M40.55,39.67a.89.89,0,0,1-.88.88H32.62v3.53h7.05a4.42,4.42,0,0,0,4.41-4.41V32.6H40.55Z"/><rect class="cls-1" x="26.45" y="40.55" width="3.53" height="3.53"/><path class="cls-1" d="M3.53,4.41a.89.89,0,0,1,.88-.88h7.05V0H4.41A4.42,4.42,0,0,0,0,4.41v7H3.53Z"/><rect class="cls-1" y="20.26" width="3.53" height="3.53"/></g></g>
                  - if @can_edit
                    .thumb_image.thumb_image-value = image_editor(project, :thumb_image)
                  .image.image-value = image_editor(project, :image)
          .actions
            a.move-to-previous href="#previous" title="#{t('global.previous')}"
              img src="#{image_path('icon-previous.png')}" alt="#{t('global.previous')}"
            a.move-to-next href="#next" title="#{t('global.next')}"
              img src="#{image_path('icon-next.png')}" alt="#{t('global.next')}"

app/views/projects/edit.html.slim
h1 Editing project

== render 'form'

= link_to 'Show', @project
'|
= link_to 'Back', projects_path

app/views/projects/index.html.slim
h1 Listing projects

table
  thead
    tr
      th Name
      th Type
      th Image
      th Summary
      th Thumb image
      th Sort order
      th
      th
      th

  tbody
    - @projects.each do |project|
      tr
        td = project.name
        td = project.type
        td = project.image
        td = project.summary
        td = project.thumb_image
        td = project.sort_order
        td = link_to 'Show', project
        td = link_to 'Edit', edit_project_path(project)
        td = link_to 'Destroy', project, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Project', new_project_path

app/views/projects/new.html.slim
h1 New project

== render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.slim
p#notice = notice

p
  strong Name:
  = @project.name
p
  strong Type:
  = @project.type
p
  strong Image:
  = @project.image
p
  strong Summary:
  = @project.summary
p
  strong Thumb image:
  = @project.thumb_image
p
  strong Sort order:
  = @project.sort_order

= link_to 'Edit', edit_project_path(@project)
'|
= link_to 'Back', projects_path